
export ZLIB_VERSION="1.2.8"
export LIBPNG_VERSION="1.6.17"
export NASM_VERSION="2.11.08"
export LIBJPEG_TURBO_VERSION="1.4.0"
export GRAPHICS_MAGICK_VERSION="1.3.21"
export REMOTE_PATH="graphicsmagick-${GRAPHICS_MAGICK_VERSION}.tgz"
export LIBPNG_REMOTE_PATH="libpng-${LIBPNG_VERSION}.tgz"
export LIBJPEG_TURBO_REMOTE_PATH="libjpeg_turbo-${LIBJPEG_TURBO_VERSION}.tgz"
export NASM_REMOTE_PATH="nasm-${NASM_VERSION}.tgz"
export ZLIB_REMOTE_PATH="zlib-${ZLIB_VERSION}.tgz"
export BUCKET_PATH="buildpack/graphicsmagick"
export S3_BUCKET="mombo-ci"
